# Generated by Django 5.0.7 on 2024-08-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
