# Generated by Django 5.0.7 on 2024-08-16 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0002_alter_category_options_alter_cour_options_and_more'),
        ('Quiz', '0002_question_explication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
