# Generated by Django 5.0.7 on 2025-01-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_alter_comment_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=800),
        ),
    ]
