# Generated by Django 5.0.7 on 2024-08-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0003_subcategory_category'),
        ('Quiz', '0003_alter_quiz_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='category',
            new_name='categorie',
        ),
        migrations.AddField(
            model_name='quiz',
            name='sub_categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MedApp.subcategory'),
            preserve_default=False,
        ),
    ]
