# Generated by Django 5.0.7 on 2024-08-31 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_rename_category_quiz_categorie_quiz_sub_categorie'),
        ('dashboard', '0003_alter_profile_approved_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.semestre'),
            preserve_default=False,
        ),
    ]
