# Generated by Django 5.0.7 on 2024-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_quiz_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Quiz_Images/'),
        ),
    ]
