# Generated by Django 5.0.7 on 2025-01-03 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(help_text='Niveau ou Semestre où les étudiants étudie.', max_length=200)),
                ('background', models.TextField(blank=True, choices=[('', 'blue'), ('card__orange', 'orange'), ('card__green', 'green')], max_length=200, null=True)),
                ('icon', models.CharField(default='ri-flashlight-line', max_length=200)),
                ('Gif_icon', models.FileField(blank=True, default=None, null=True, upload_to='gif_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.FileField(blank=True, help_text='Profile picture', null=True, upload_to='Profile-pic')),
                ('date_of_birth', models.DateField(blank=True, help_text='Birth Day', null=True)),
                ('approved', models.BooleanField(default=True, help_text='Is the profile is approved')),
                ('user', models.OneToOneField(help_text='User linked to this profile', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semestre', models.ManyToManyField(help_text='hold the ctrl key and select all the available choices', to='dashboard.semestre')),
            ],
        ),
    ]
