# Generated by Django 5.0.7 on 2024-08-06 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='approved',
            field=models.BooleanField(default=False, help_text='Is the profile is approved'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Birth Day', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='Profile-pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semestre',
            field=models.ForeignKey(blank=True, help_text='the Semestre', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.semestre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='User linked to this profile', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='semestre',
            field=models.CharField(help_text='Niveau ou Semestre où les étudiants étudie.', max_length=200),
        ),
    ]
