# Generated by Django 5.0.7 on 2024-09-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_profile_approved_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='semestre',
        ),
        migrations.AddField(
            model_name='profile',
            name='semestre',
            field=models.ManyToManyField(default=1, help_text='hold the ctrl key and select all the available choices', to='dashboard.semestre'),
        ),
    ]
