# Generated by Django 5.0.7 on 2024-09-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_profile_semestre_profile_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='semestre',
            field=models.ManyToManyField(help_text='hold the ctrl key and select all the available choices', to='dashboard.semestre'),
        ),
    ]
