# Generated by Django 5.0.7 on 2024-09-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_profile_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.FileField(blank=True, help_text='Profile picture', null=True, upload_to='Profile-pic'),
        ),
    ]
