# Generated by Django 5.0.7 on 2024-09-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='background',
            field=models.TextField(choices=[('', 'blue'), ('card__orange', 'orange'), ('card__green', 'green')], default=2, max_length=200),
            preserve_default=False,
        ),
    ]
