# Generated by Django 5.0.7 on 2024-09-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_semestre_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='icon',
            field=models.CharField(default='ri-flashlight-line', max_length=200),
        ),
    ]
