# Generated by Django 5.0.7 on 2024-09-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_semestre_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='background',
            field=models.TextField(blank=True, choices=[('', 'blue'), ('card__orange', 'orange'), ('card__green', 'green')], max_length=200, null=True),
        ),
    ]
