# Generated by Django 5.0.7 on 2024-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_semestre_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='approved',
            field=models.BooleanField(default=True, help_text='Is the profile is approved'),
        ),
    ]
