# Generated by Django 5.0.7 on 2025-01-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('background', models.TextField(blank=True, choices=[('', 'blue'), ('card__orange', 'orange'), ('card__green', 'green')], max_length=200, null=True)),
                ('Gif_icon', models.FileField(blank=True, default=None, null=True, upload_to='gif_icons')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.semestre')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Cour/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.category')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.semestre')),
            ],
            options={
                'verbose_name': 'Cour',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Résumé/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.category')),
            ],
            options={
                'verbose_name': 'Résumé',
                'verbose_name_plural': 'Résumés',
            },
        ),
        migrations.CreateModel(
            name='support_cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Support du cour/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.category')),
            ],
            options={
                'verbose_name': 'Support du cour',
                'verbose_name_plural': 'Support du cours',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Videos/')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.semestre')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
