# Generated by Django 5.0.7 on 2024-08-05 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Résumé/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.category')),
                ('sub_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedApp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Cour/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.category')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.semestre')),
                ('sub_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedApp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='support_cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='Support du cour/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.category')),
                ('sub_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedApp.subcategory')),
            ],
        ),
    ]
