# Generated by Django 5.0.7 on 2024-08-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cour',
            options={'verbose_name': 'Cour', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Résumé', 'verbose_name_plural': 'Résumés'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='support_cour',
            options={'verbose_name': 'Support du cour', 'verbose_name_plural': 'Support du cours'},
        ),
    ]
