# Generated by Django 5.0.7 on 2024-08-19 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0002_alter_category_options_alter_cour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MedApp.category'),
            preserve_default=False,
        ),
    ]
