# Generated by Django 5.0.7 on 2024-08-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0005_alter_category_semestre_alter_subcategory_semestre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
    ]
