# Generated by Django 5.0.7 on 2024-08-31 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sous Module', 'verbose_name_plural': 'Sous Modules'},
        ),
    ]
