# Generated by Django 5.0.7 on 2024-08-31 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0007_alter_subcategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='sous_module',
        ),
    ]
