# Generated by Django 5.0.7 on 2024-09-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0008_rename_category_category_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
