# Generated by Django 5.0.7 on 2024-09-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0012_alter_category_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background',
            field=models.TextField(choices=[('', 'blue'), ('card__orange', 'orange'), ('card__green', 'green')], max_length=200),
        ),
    ]
